pool:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: Build
  steps:
  - script: docker build -t notificus/configuration-service .
  
- job: Publish
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - script: |
    docker login -u notificus -p c2Mwk-Mc
    docker push notificus/configuration-service
