version: '3.3'
services:
  configuration-service:
    container_name: configuration-service
    build:
      context: .
      dockerfile: Dockerfile
    image: pgarneau/configuration-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=7777
    expose:
      - 7777
    ports:
      - 7777:7777
    networks:
      - notificus-network

  notification-service:
    container_name: notification-service
    build:
      context: /home/philippe/dev/git/notification-service
      dockerfile: Dockerfile
    image: pgarneau/notification-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9999
    expose:
      - 9999
    ports:
      - 9999:9999
    networks:
      - notificus-network
    links:
      - configuration-service:configuration-service
    depends_on:
      - configuration-service

  configuration-web-app:
    container_name: configuration-web-app
    build:
      context: /home/philippe/dev/git/configuration-web-app-angular
      dockerfile: Dockerfile
    image: pgarneau/configuration-web-app:latest
    expose:
      - 4200
      - 4000
    ports:
      - 4000:4000
      - 4200:4200
    tty: true
    networks:
      - notificus-network

networks:
  notificus-network:
    driver: bridge
