spring:
  profiles: default
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/pgarneau
#    username: pgarneau
    url: jdbc:postgresql://zeus.gel.usherbrooke.ca:5432/s6infoe02
    username: s6infoe02
    password: s6infoe02
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  use-forward-headers: true

configuration-service:
  url: "http://localhost"

configuration-web-app:
  url: "http://localhost:8080/home"
  ip: "localhost"

notification-service:
  ip: "localhost"

---

spring:
  profiles: prod
  datasource:
    platform: postgres
    url: jdbc:postgresql://zeus.gel.usherbrooke.ca:5432/s6infoe02
    username: s6infoe02
    password: s6infoe02
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 7777
  use-forward-headers: true

configuration-service:
  url: "http://localhost"

configuration-web-app:
  url: "http://localhost:8080/home"
  ip: "configuration-web-app"

notification-service:
  ip: "notification-service"
