spring:
  profiles: default
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/pgarneau
#    username: pgarneau
    url: jdbc:postgresql://zeus.gel.usherbrooke.ca:5432/s6infoe02
    username: s6infoe02
    password: s6infoe02
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  use-forward-headers: true

configuration-service:
  url: "http://localhost"

configuration-web-app:
  url: "http://localhost:8080/home"
  ip: "localhost"

notification-service:
  ip: "localhost"

---

spring:
  profiles: prod
  datasource:
    platform: postgres
    url: jdbc:postgresql://zeus.gel.usherbrooke.ca:5432/s6infoe02
    username: s6infoe02
    password: s6infoe02
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 7777
  use-forward-headers: true

configuration-service:
  url: "http://localhost"

configuration-web-app:
  url: "http://localhost:8080/home"
  ip: "configuration-web-app"

notification-service:
  ip: "notification-service"

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb:DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console: true
    path: /console
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      dialect:
        org.hibernate.dialect.H2Dialect

server:
  use-forward-headers: true
  port: 8081

configuration-service:
  url: "http://localhost"

configuration-web-app:
  url: "http://localhost:8080/home"
  ip: "localhost"

notification-service:
  ip: "localhost"
